### ISSUE TITLE
Livonia areas keys do not work

### ISSUE THREAD

**Issue by ksmnt12** [1Hyena/aronia#4]
There is discrepancy between key vnums assigned to exits in "Livonia" areas and actual key vnums. Keys have been assigned new vnums when imported to Aronia but exits in areas have not been updated accordingly.

For example 1:

Name:       [Eremite's cave]
Area:       [   79] Forgotten Mines
-Up    to [107022] Key: [ 7001] Size: [  huge] Exit flags: [DOOR CLOSED]

There is no key with vnum 7001. The key for this door should be  a rusty minekey [#107001]

Example 2:

Name:       [Center hall of Upper spheres of Empyrean]
Area:       [    4] Empyrean
-Up    to [111670] Key: [11604] Size: [  huge] Exit flags: [DOOR CLOSED LOCKED PICKPROOF NOPASS UNBREAK]

There is no key with vnum 11604. The key for this door should be  Tooni's talking key whispers: "look at me" [#111604]

**Comment by 1Hyena** [comment]
this should be fixed now
