### ISSUE TITLE
Character's attributes do not reset when ironman character becomes a ghost. Bug or Feature?

### ISSUE THREAD

**Issue by ksmnt12** [1Hyena/aronia#5]
When an ironman character dies and goes to Origination room then it maintains the attributes of the original character. It is possible to leave without any change. So it is possible to create a Ghost mage with for example Giant mage's attributes.
![image](https://github.com/user-attachments/assets/7456eef3-fbaa-44d2-8f70-3eaf074f2bc7)

**Comment by 1Hyena** [comment]
this was a bug and is fixed now. only wights, ghouls and liches get to keep their original stats
